### PR TITLE
Fix missing staff in Telemann Concert

### LINKED ISSUE #59: Broken grand staff in Telemann Concert
Starting from m. 59, I suppose there was some broken conversion from MusicXML. [All the organ part is written on a single staff](https://github.com/music-encoding/sample-encodings/blob/9ebd87b354e992eb6c061eded1c989640b889b05/MEI_4.0/Music/Complete_examples/Telemann_Concert.mei#L6290) there.

### PR DESCRIPTION
**Pull request by rettinghaus**
fixes #59

### CODE REVIEW

**Review by th-we — APPROVED** [review]
Solves the problem. Thanks, Klaus!

**Comment by musicEnfanthen** [comment]
Thanks @rettinghaus . `staff n="6"` now always has `layer n="2"` or `n="3"` as first child, right?

**Comment by rettinghaus** [comment]
@musicEnfanthen correct.

**Comment by musicEnfanthen** [comment]
I see. Would it make sense to renumber the layers in the new sixth staff to start with n=1?

**Review by bwbohl — APPROVED** [review]
The question concerning the value of `staff[n='6']/@n` makes me wonder if it's ok according to schema and guidelines the way it is right now, as `@n`:

> Provides a numeric designation that indicates an element's position in a sequence of similar elements. Its value must be a non-negative integer. Value of datatype nonNegativeInteger.

And there is no rule that a sequence of numbers has to start with `1`.

 Nevertheless, the guidelines state:

>As the order of the staff elements in the file does not have to reflect their order in the original document, to eliminate confusion, they should always refer to a [staffDef](https://music-encoding.org/guidelines/v4/elements/staffdef.html) element, using either an `@n` or `@def` attribute. Whereas the `@def` attribute uses the xs:anyURI datatype, the `@n` value refers to the closest preceding [staffDef](https://music-encoding.org/guidelines/v4/elements/staffdef.html) or [layerDef](https://music-encoding.org/guidelines/v4/elements/layerdef.html) with the same value in its `@n` attribute.
> [figure omitted]
> Each [staff](https://music-encoding.org/guidelines/v4/elements/staff.html) may hold a number of [layer](https://music-encoding.org/guidelines/v4/elements/layer.html) elements to reflect multiple ‘voices’. Just as with [staff](https://music-encoding.org/guidelines/v4/elements/staff.html), the order of the [layer](https://music-encoding.org/guidelines/v4/elements/layer.html) elements in the file does not have to reflect their original order in the document, so they also possess `@n` and `@def` attributes for association with the appropriate layer definition.

These passages say "should", nevertheless I think in terms of best practice (which should be illustrated by the sample encoding), all the layers should also be defined in the `scoreDef`, and either `@def`or `@n`should always be used to link staffs, layers and their respective definitions.

But this might be another issue!

**Pull request merged**
