### PR TITLE
Add missing durations

### PR DESCRIPTION
**Pull request by th-we**

### CODE REVIEW

**Comment by th-we** [comment]
Sorry, accidentally deleted the branch

**Comment by rettinghaus** [comment]
@th-we could you please resolve the conflicts?

**Review by bwbohl — APPROVED** [review]
looks good to me

**Comment by rettinghaus** [comment]
still conflicting

**Comment by rettinghaus** [comment]
@th-we would you be so kind to remove the conflicts? Otherwise we should close this PR.

**Comment by musicEnfanthen** [comment]
@th-we Any chance that you would be able to resolve the conflicts? It seems that these are only connected to different formatting of the files.

**Comment by th-we** [comment]
Instead of resolving the conflicts, I created PR #71.

**Pull request closed without merging**
