### PR TITLE
Fixed some validation errors

### PR DESCRIPTION
**Pull request by rettinghaus**
Fixed several encoding errors

### CODE REVIEW

**Comment by ahankinson** [comment]
Thanks, Klaus. Have you validated these changes against MEI 3.0.0? If so, and they pass, then I'll merge them in.

**Comment by rettinghaus** [comment]
I double checked them. (And even found a typo that wasn't by me.) 
So the files should be fine now.

**Comment by ahankinson** [comment]
OK, so they validate? I didn't validate them, but if you did and they pass, that's fine.

**Comment by rettinghaus** [comment]
That's what I meant. They validate.

**Pull request merged**
